backend:
  name: github
  repo: danevskiy/landings
  branch: main
  auth_type: implicit
  app_id: Ov23liBRLQNpg9ZYwLcL

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "landings"
    label: "Лендинги"
    folder: "src/content/landings"
    extension: "yaml"
    format: "yaml"
    create: true
    slug: "{{slug}}"

    fields:
      - { label: "Url", name: "title", widget: "string" }

      - label: "Блоки"
        name: "blocks"
        widget: "list"
        types:

          - label: "Header Block"
            name: "header"
            widget: "object"
            fields:
              - { label: "Тип", name: "type", widget: "hidden", default: "header" }
              - { label: "Логотип", name: "logo", widget: "image" }
              - label: "Меню"
                name: "menu"
                widget: "list"
                fields:
                  - { label: "Название", name: "name", widget: "string" }
                  - { label: "Ссылка", name: "href", widget: "string" }

          - label: "Breadcrumbs Block"
            name: "breadcrumbs"
            widget: "object"
            fields:
              - { label: "Тип", name: "type", widget: "hidden", default: "breadcrumbs" }
              - label: "Список хлебных крошек"
                name: "list"
                widget: "list"
                fields:
                  - { label: "ID", name: "id", widget: "number" }
                  - { label: "Ссылка", name: "href", widget: "string", required: false }
                  - { label: "Название", name: "name", widget: "string" }

          - label: "Product Block"
            name: "product"
            widget: "object"
            fields:
              - { label: "ID", name: "id", widget: "number",  required: false }
          
          - label: "Categories Block"
            name: "categories"
            widget: "object"
            fields:
              - { label: "ID", name: "id", widget: "number",  required: false }

          
